name: envAITA
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - xarray
  - scikit-learn
  - scikit-image
  - ipywidgets
  - ipympl
  - scipy
  - tqdm
  - datetime
  - pip
  - pip:
    - -e git+https://github.com/ThomasChauve/xarray_uvecs.git@main#egg=xarrayuvecs
    - -e git+https://github.com/ThomasChauve/xarray_aita.git@main#egg=xarrayaita
