name: envAITA
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - xarray
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    - -e git+https://github.com/ThomasChauve/xarray_uvecs.git#egg=xarray_uvecs
    - -e git+https://github.com/ThomasChauve/xarray_aita.git#egg=xarray_uvecs
