name: envAITA
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - ipywidgets
  - ipympl
  - pip
  - pip:
    - -e git+https://github.com/ThomasChauve/xarray_aita.git@main#egg=xarrayaita
    - -e git+https://github.com/ThomasChauve/xarray_uvecs.git@main#egg=xarrayuvecs